---
title: "Gov 50 Final Project"
author: "Sasha Hitachi"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project proposal

Do the ideological directions of decisions made by federal circuit judges match the predominant ideological leanings of the state or territory in which the case was decided? For example, within two cases that are similar in nature, is a judge based in Tennessee more likely to decide the case conservatively as compared to a judge in Massachusetts? I expect that outcomes of cases decided in traditionally conservative states will also trend conservative, while the outcomes of cases in traditionally liberal states will trend liberal. I intend to measure whether a state is conservative, liberal, or a swing state using election outcomes from 2008 and 2012 Presidential Elections. I will then take case data from federal circuit courts between the years 2008-2012 and using an explanatory variable of interest (which state the case was decided in), measure the outcome variable whether the case was decided liberally =1 or conservatively = 0. I will also group by case type to ensure I am comparing cases that are similar in nature. For example, Commercial Regulation cases are coded as 18, and Freedom of Expression cases are coded as 13. After grouping by type of case, I will measure the average decision outcome (conservative or liberal) by state and compare them. The above variables are measured using Robert Carp and Kenneth Manning's "U.S. District Court Database" dataset. After conducting this analysis, an average nearing 0 for conservative vs. liberal case outcomes would support my hypothesis that cases decided in red states are typically more conservative. Likewise, an average nearing 1 for case outcomes in liberal states would support a hypothesis that decisions made in blue electorate states are more liberal. 

## Proposed dataset
Robert A. Carp and Kenneth L. Manning. 2016. “U.S.District Court Database.” 2016 version n=110977.
URL: http://districtcourtdatabase.org

## Visualizations
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(readxl)

fdcdata <- read_excel("data/fdcdata_thru_2012.xlsx")

fdcdata <- fdcdata |>
  filter(year >= 2008) |>
  mutate(judge_party = case_when(
    party == 1 ~ "Democrat",
    party == 2 ~ "Republican",
    party == 99 ~ "Independent / Other / Unknown"))|>
  mutate(case_outcome = if_else(libcon == 1, "Liberal", "Conservative"))

party_by_case_outcome <- fdcdata |>
  group_by(judge_party) |>
  summarize(case_average = mean(libcon),
            case_sd = sd(libcon))
  
  knitr::kable(party_by_case_outcome, col.names = c("Judge Party", "Case Outcome Average", "Case Outcome SD"), digits = 3)





```
Based on the above data, across all judges surveyed during and after the year 2008, the average outcome of cases decided by Democrat judges was 0.466, with 0 being the case was decided against the defendant and 1 being in favor of the defendant. Average outcome for cases decided by Republican judges was 0.372, showing that on average, Republican judges are more likely to decide cases conservatively (against the defendant). Within the group of judges who are Independent or whose political affiliation is unknown, average case outcome fell between Democrat and Republican outcomes at 0.420. 


